#!/usr/bin/env python3
"""
Convert Birchington OSM (Overpass JSON) → game-coordinate SVG.

Reads:  manus-output/birchie-osm/birchington.json
Writes: apps/game/public/admin/scene-assets/birchie-map/birchie-roads.svg

The output SVG has:
  - <g id="coastline"> with the sea boundary
  - <g id="green-areas"> with all parks/grass/leisure polygons
  - <g id="roads-{class}"> per road class (trunk, tertiary, residential, etc.)
  - Each <path> has data-name + id (slugified name) so we can target landmarks
  - <rect id="arc-plot"> marking the long narrow green between Viking Close + Canute Road

Lat/lng → canvas via simple linear projection (good enough for the
~1.5km × 700m area we care about).
"""
import json, re, math
from pathlib import Path

ROOT = Path(__file__).parent.parent
OSM = ROOT / "manus-output/birchie-osm/birchington.json"
OUT = ROOT / "apps/game/public/admin/scene-assets/birchie-map/birchie-roads.svg"

# Focused bbox: Minnis Bay (west) → Birchington centre (east), trimmed to fit the play area
LAT_MIN, LAT_MAX = 51.3760, 51.3855
LON_MIN, LON_MAX = 1.2780, 1.3120

SVG_W, SVG_H = 2400, 800

# Latitude correction factor — flatten east/west axis to match real-world metres
# At 51.4°N: 1° lat ≈ 111.0km, 1° lon ≈ 69.4km
LAT_M_PER_DEG = 111000
LON_M_PER_DEG = 111000 * math.cos(math.radians(51.4))


def project(lat, lon):
    """Lat/lon → canvas px (north up, west left)."""
    x = (lon - LON_MIN) / (LON_MAX - LON_MIN) * SVG_W
    y = (LAT_MAX - lat) / (LAT_MAX - LAT_MIN) * SVG_H
    # Latitude correction: stretch X to match real-world metric
    real_w = (LON_MAX - LON_MIN) * LON_M_PER_DEG
    real_h = (LAT_MAX - LAT_MIN) * LAT_M_PER_DEG
    aspect_real = real_w / real_h
    aspect_svg = SVG_W / SVG_H
    if aspect_real > aspect_svg:
        # Stretch height (already proportional)
        pass
    return x, y


def xml_attr(s):
    """Escape string for safe use as XML attribute value."""
    if not s: return ''
    return s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-")


def way_to_path_d(pts):
    """List of (lat, lon) → SVG path d attribute."""
    if not pts:
        return ""
    parts = []
    for i, (lat, lon) in enumerate(pts):
        x, y = project(lat, lon)
        parts.append(f"{'M' if i == 0 else 'L'}{x:.1f},{y:.1f}")
    return "".join(parts)


def main():
    src = json.loads(OSM.read_text())

    # Group ways
    roads = {
        "trunk": [], "primary": [], "secondary": [], "tertiary": [],
        "unclassified": [], "residential": [], "service": [],
        "footway": [], "track": [], "path": [], "pedestrian": [],
    }
    coastline = []
    green = []  # leisure / parks / grass / pitches / sports
    pools = []
    
    for el in src["elements"]:
        if el.get("type") != "way" or "geometry" not in el:
            continue
        tags = el.get("tags", {})
        pts = [(g["lat"], g["lon"]) for g in el["geometry"]]
        # Skip if entirely outside bbox
        if not any(LAT_MIN <= la <= LAT_MAX and LON_MIN <= lo <= LON_MAX for la, lo in pts):
            continue
        name = tags.get("name", "")
        
        if "highway" in tags:
            cls = tags["highway"]
            if cls in roads:
                roads[cls].append({"name": name, "pts": pts, "id": el["id"]})
            else:
                roads["residential"].append({"name": name, "pts": pts, "id": el["id"]})
        elif tags.get("natural") == "coastline":
            coastline.append({"pts": pts})
        elif tags.get("leisure") in ("park", "garden", "recreation_ground", "playground", "sports_centre", "pitch", "common"):
            green.append({"name": name, "kind": tags["leisure"], "pts": pts})
        elif tags.get("landuse") in ("grass", "meadow", "recreation_ground"):
            green.append({"name": name, "kind": tags["landuse"], "pts": pts})
        elif tags.get("leisure") == "swimming_pool":
            pools.append({"pts": pts})
    
    # Build SVG
    out = []
    out.append(f'<?xml version="1.0" encoding="UTF-8"?>')
    out.append(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SVG_W} {SVG_H}" width="{SVG_W}" height="{SVG_H}">')
    out.append(f'<!-- Birchington geography from OpenStreetMap (© OpenStreetMap contributors, ODbL).')
    out.append(f'     Generated by tools/osm-to-svg.py. Bbox: lat {LAT_MIN}..{LAT_MAX}, lon {LON_MIN}..{LON_MAX}. -->')
    
    # Background sea = whole canvas (will be clipped by land coastline overlay)
    out.append(f'<rect id="sea-bg" width="{SVG_W}" height="{SVG_H}" fill="#bfdde3"/>')
    
    # Land — synthesise as a polygon south of the coastline
    if coastline:
        # Combine all coastline ways into one big land polygon
        # Coastline runs west→east; land is south of it
        all_coast_pts = []
        for c in coastline:
            all_coast_pts.extend(c["pts"])
        # Sort by longitude (west to east)
        all_coast_pts.sort(key=lambda p: p[1])
        d = "M"
        for i, (lat, lon) in enumerate(all_coast_pts):
            x, y = project(lat, lon)
            d += f"{x:.1f},{y:.1f} "
            if i > 0:
                d = d.replace(" ", "L", 1) if "L" not in d.split("M")[-1] else d
        # Close to bottom-right and bottom-left
        d += f"L{SVG_W},{SVG_H} L0,{SVG_H} Z"
        out.append(f'<path id="land" d="{d}" fill="#dec98a"/>')
    else:
        out.append(f'<rect id="land" width="{SVG_W}" height="{SVG_H}" fill="#dec98a"/>')
    
    # Green areas — fill polygons
    out.append('<g id="green-areas" fill="#a8c890" stroke="#78a06a" stroke-width="1.5">')
    for g in green:
        d = way_to_path_d(g["pts"])
        if not d: continue
        d_closed = d + " Z"
        sl = slug(g["name"]) or f"green-{g['kind']}"
        out.append(f'  <path id="{sl}" data-name="{xml_attr(g["name"] or "")}" data-kind="{g["kind"]}" d="{d_closed}"/>')
    out.append('</g>')
    
    # Pools (Minnis Bay paddling pool)
    out.append('<g id="pools" fill="#7cc6e0" stroke="#4d97b3" stroke-width="1.5">')
    for p in pools:
        d = way_to_path_d(p["pts"]) + " Z"
        out.append(f'  <path d="{d}"/>')
    out.append('</g>')
    
    # Roads — by class
    road_styles = {
        "trunk":        ('#f0c870', '#a8865e', 16, 'trunk'),
        "primary":      ('#f0c870', '#a8865e', 14, 'primary'),
        "secondary":    ('#f0d894', '#a8865e', 12, 'secondary'),
        "tertiary":     ('#f0e3b0', '#a8865e', 10, 'tertiary'),
        "unclassified": ('#f6ecc7', '#b89f6c', 8, 'unclassified'),
        "residential":  ('#fdf6dc', '#c8b58a', 8, 'residential'),
        "service":      ('#fdf6dc', '#c8b58a', 5, 'service'),
        "footway":      ('#e8d49a', '#a8865e', 3, 'footway-dashed'),
        "track":        ('#e8d49a', '#a8865e', 4, 'track-dashed'),
        "pedestrian":   ('#f0e3b0', '#a8865e', 8, 'pedestrian'),
        "path":         ('#e8d49a', '#a8865e', 3, 'path-dashed'),
    }
    
    for cls, ways in roads.items():
        if not ways:
            continue
        fill, edge, width, style_class = road_styles[cls]
        dasharray = ' stroke-dasharray="4 3"' if 'dashed' in style_class else ''
        out.append(f'<g id="roads-{cls}" stroke="{fill}" stroke-width="{width}" fill="none" stroke-linecap="round" stroke-linejoin="round"{dasharray}>')
        for w in ways:
            d = way_to_path_d(w["pts"])
            if not d: continue
            sl = slug(w["name"]) or f"r-{w['id']}"
            out.append(f'  <path id="{sl}" data-name="{xml_attr(w["name"])}" data-cls="{cls}" d="{d}"/>')
        out.append('</g>')
        # Edge stroke ABOVE for painted look
    
    # A.R.C. plot — mark the green between Viking Close + Canute Road
    arc_plot_lat = 51.37827
    arc_plot_lon = 1.28632
    arc_x, arc_y = project(arc_plot_lat, arc_plot_lon)
    # Plot dimensions: ~158m N-S × ~50m E-W (narrow)
    plot_h_deg = 158 / LAT_M_PER_DEG
    plot_w_deg = 50 / LON_M_PER_DEG
    # Project corners
    nx, ny = project(arc_plot_lat + plot_h_deg/2, arc_plot_lon - plot_w_deg/2)
    sx, sy = project(arc_plot_lat - plot_h_deg/2, arc_plot_lon + plot_w_deg/2)
    plot_w_px = abs(sx - nx)
    plot_h_px = abs(sy - ny)
    out.append(f'<rect id="arc-plot" data-name="A.R.C. site" x="{nx:.1f}" y="{ny:.1f}" width="{plot_w_px:.1f}" height="{plot_h_px:.1f}" fill="#e3b04b" fill-opacity="0.55" stroke="#7b5c3a" stroke-width="3" stroke-dasharray="6 4"/>')
    out.append(f'<text x="{(nx+sx)/2:.1f}" y="{(ny+sy)/2:.1f}" font-family="Fredoka, sans-serif" font-size="20" font-weight="700" fill="#3a3a3a" text-anchor="middle">A.R.C.</text>')
    
    out.append('</svg>')
    
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")
    print(f"  {sum(len(v) for v in roads.values())} roads, {len(green)} green areas, {len(pools)} pools, 1 coastline")


if __name__ == "__main__":
    main()
